version: '3.7'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
        
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
